version: '3'

services:
  server:
    container_name: mc-server
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: 'TRUE'
      MEMORY: 2G
      EXEC_DIRECTLY: 'true'
    env_file:
      - .env
    volumes:
      - server-data:/data
    restart: unless-stopped

  backup:
    container_name: mc-backup
    build:
      context: ./cron-backup
      args:
        BACKUP_CRONTAB: 0 */6 * * *
    environment:
      BACKUP_COUNT_LIMIT: '12'
      STARTUP_DELAY: 15s
    volumes:
      - server-data:/source
      - ./backups:/destination:z
    restart: unless-stopped

volumes:
  server-data:
